version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik/config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.docker.localhost`)"
      - "traefik.http.routers.phpmyadmin.tls=true"

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.docker.localhost`)"
      - "traefik.http.routers.adminer.tls=true"

  mysql_5.6:
    image: mysql:5.6
    container_name: mysql_5.6
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes: 
      - mysql_5.6:/var/lib/mysql

  mysql_5.7:
    image: mysql:5.7
    container_name: mysql_5.7
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes: 
      - mysql_5.7:/var/lib/mysql

  mysql_8.0:
    image: mysql:8.0
    container_name: mysql_8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes: 
      - mysql_8.0:/var/lib/mysql

  postgres_13:
    image: postgres:13
    container_name: postgres_13
    env_file:
      - .env
    volumes: 
      - postgres_13:/var/lib/postgresql/data

volumes:
  mysql_5.6:
  mysql_5.7:
  mysql_8.0:
  postgres_13: